<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260701001414 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, notes TEXT DEFAULT NULL, session_id INT NOT NULL, exercise_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC74095A613FECDF ON activity (session_id)');
        $this->addSql('CREATE INDEX IDX_AC74095AE934951A ON activity (exercise_id)');
        $this->addSql('CREATE TABLE activity_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, actual_value DOUBLE PRECISION NOT NULL, notes TEXT DEFAULT NULL, session_log_id INT NOT NULL, activity_id INT NOT NULL, metric_definition_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FD06F647850C57DF ON activity_log (session_log_id)');
        $this->addSql('CREATE INDEX IDX_FD06F64781C06096 ON activity_log (activity_id)');
        $this->addSql('CREATE INDEX IDX_FD06F647A9425B7A ON activity_log (metric_definition_id)');
        $this->addSql('CREATE TABLE activity_metric (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, planned_value DOUBLE PRECISION DEFAULT NULL, activity_id INT NOT NULL, metric_definition_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D5A0CEE381C06096 ON activity_metric (activity_id)');
        $this->addSql('CREATE INDEX IDX_D5A0CEE3A9425B7A ON activity_metric (metric_definition_id)');
        $this->addSql('CREATE TABLE exercise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, muscle_groups JSON DEFAULT NULL, equipment JSON DEFAULT NULL, type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AEDAD51CC54C8C93 ON exercise (type_id)');
        $this->addSql('CREATE TABLE exercise_metric_default (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, default_value DOUBLE PRECISION DEFAULT NULL, exercise_id INT NOT NULL, metric_definition_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3D272021E934951A ON exercise_metric_default (exercise_id)');
        $this->addSql('CREATE INDEX IDX_3D272021A9425B7A ON exercise_metric_default (metric_definition_id)');
        $this->addSql('CREATE TABLE exercise_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, category VARCHAR(100) DEFAULT NULL, sport_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D5FB359BAC78BCF8 ON exercise_type (sport_id)');
        $this->addSql('CREATE TABLE goal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, target_value DOUBLE PRECISION DEFAULT NULL, unit VARCHAR(50) DEFAULT NULL, current_value DOUBLE PRECISION DEFAULT NULL, target_date DATE DEFAULT NULL, achieved_at DATE DEFAULT NULL, notes TEXT DEFAULT NULL, metric_definition_id INT DEFAULT NULL, program_id INT NOT NULL, week_id INT DEFAULT NULL, sport_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FCDCEB2EA9425B7A ON goal (metric_definition_id)');
        $this->addSql('CREATE INDEX IDX_FCDCEB2E3EB8070A ON goal (program_id)');
        $this->addSql('CREATE INDEX IDX_FCDCEB2EC86F3B2F ON goal (week_id)');
        $this->addSql('CREATE INDEX IDX_FCDCEB2EAC78BCF8 ON goal (sport_id)');
        $this->addSql('CREATE TABLE metric_definition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, unit VARCHAR(30) NOT NULL, type VARCHAR(20) NOT NULL, sport_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DADB9D15AC78BCF8 ON metric_definition (sport_id)');
        $this->addSql('CREATE TABLE personal_record (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value DOUBLE PRECISION NOT NULL, achieved_at DATE NOT NULL, notes TEXT DEFAULT NULL, exercise_id INT NOT NULL, metric_definition_id INT NOT NULL, session_log_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6FB87386E934951A ON personal_record (exercise_id)');
        $this->addSql('CREATE INDEX IDX_6FB87386A9425B7A ON personal_record (metric_definition_id)');
        $this->addSql('CREATE INDEX IDX_6FB87386850C57DF ON personal_record (session_log_id)');
        $this->addSql('CREATE TABLE program (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, status VARCHAR(255) DEFAULT \'draft\' NOT NULL, is_template BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE program_week (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, week_number INT NOT NULL, status VARCHAR(255) DEFAULT \'normal\' NOT NULL, notes TEXT DEFAULT NULL, program_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_56BC3CC73EB8070A ON program_week (program_id)');
        $this->addSql('CREATE TABLE session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day_of_week INT NOT NULL, position INT NOT NULL, status VARCHAR(255) DEFAULT \'planned\' NOT NULL, scheduled_date DATE DEFAULT NULL, notes TEXT DEFAULT NULL, week_id INT NOT NULL, sport_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D044D5D4C86F3B2F ON session (week_id)');
        $this->addSql('CREATE INDEX IDX_D044D5D4AC78BCF8 ON session (sport_id)');
        $this->addSql('CREATE TABLE session_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, duration_minutes INT DEFAULT NULL, rating INT DEFAULT NULL, notes TEXT DEFAULT NULL, session_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F2E6F0FF613FECDF ON session_log (session_id)');
        $this->addSql('CREATE TABLE sport (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, icon VARCHAR(50) DEFAULT NULL, color VARCHAR(7) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095A613FECDF FOREIGN KEY (session_id) REFERENCES session (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095AE934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_log ADD CONSTRAINT FK_FD06F647850C57DF FOREIGN KEY (session_log_id) REFERENCES session_log (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_log ADD CONSTRAINT FK_FD06F64781C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_log ADD CONSTRAINT FK_FD06F647A9425B7A FOREIGN KEY (metric_definition_id) REFERENCES metric_definition (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_metric ADD CONSTRAINT FK_D5A0CEE381C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_metric ADD CONSTRAINT FK_D5A0CEE3A9425B7A FOREIGN KEY (metric_definition_id) REFERENCES metric_definition (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exercise ADD CONSTRAINT FK_AEDAD51CC54C8C93 FOREIGN KEY (type_id) REFERENCES exercise_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exercise_metric_default ADD CONSTRAINT FK_3D272021E934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exercise_metric_default ADD CONSTRAINT FK_3D272021A9425B7A FOREIGN KEY (metric_definition_id) REFERENCES metric_definition (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exercise_type ADD CONSTRAINT FK_D5FB359BAC78BCF8 FOREIGN KEY (sport_id) REFERENCES sport (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE goal ADD CONSTRAINT FK_FCDCEB2EA9425B7A FOREIGN KEY (metric_definition_id) REFERENCES metric_definition (id)');
        $this->addSql('ALTER TABLE goal ADD CONSTRAINT FK_FCDCEB2E3EB8070A FOREIGN KEY (program_id) REFERENCES program (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE goal ADD CONSTRAINT FK_FCDCEB2EC86F3B2F FOREIGN KEY (week_id) REFERENCES program_week (id)');
        $this->addSql('ALTER TABLE goal ADD CONSTRAINT FK_FCDCEB2EAC78BCF8 FOREIGN KEY (sport_id) REFERENCES sport (id)');
        $this->addSql('ALTER TABLE metric_definition ADD CONSTRAINT FK_DADB9D15AC78BCF8 FOREIGN KEY (sport_id) REFERENCES sport (id)');
        $this->addSql('ALTER TABLE personal_record ADD CONSTRAINT FK_6FB87386E934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE personal_record ADD CONSTRAINT FK_6FB87386A9425B7A FOREIGN KEY (metric_definition_id) REFERENCES metric_definition (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE personal_record ADD CONSTRAINT FK_6FB87386850C57DF FOREIGN KEY (session_log_id) REFERENCES session_log (id)');
        $this->addSql('ALTER TABLE program_week ADD CONSTRAINT FK_56BC3CC73EB8070A FOREIGN KEY (program_id) REFERENCES program (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT FK_D044D5D4C86F3B2F FOREIGN KEY (week_id) REFERENCES program_week (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT FK_D044D5D4AC78BCF8 FOREIGN KEY (sport_id) REFERENCES sport (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session_log ADD CONSTRAINT FK_F2E6F0FF613FECDF FOREIGN KEY (session_id) REFERENCES session (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity DROP CONSTRAINT FK_AC74095A613FECDF');
        $this->addSql('ALTER TABLE activity DROP CONSTRAINT FK_AC74095AE934951A');
        $this->addSql('ALTER TABLE activity_log DROP CONSTRAINT FK_FD06F647850C57DF');
        $this->addSql('ALTER TABLE activity_log DROP CONSTRAINT FK_FD06F64781C06096');
        $this->addSql('ALTER TABLE activity_log DROP CONSTRAINT FK_FD06F647A9425B7A');
        $this->addSql('ALTER TABLE activity_metric DROP CONSTRAINT FK_D5A0CEE381C06096');
        $this->addSql('ALTER TABLE activity_metric DROP CONSTRAINT FK_D5A0CEE3A9425B7A');
        $this->addSql('ALTER TABLE exercise DROP CONSTRAINT FK_AEDAD51CC54C8C93');
        $this->addSql('ALTER TABLE exercise_metric_default DROP CONSTRAINT FK_3D272021E934951A');
        $this->addSql('ALTER TABLE exercise_metric_default DROP CONSTRAINT FK_3D272021A9425B7A');
        $this->addSql('ALTER TABLE exercise_type DROP CONSTRAINT FK_D5FB359BAC78BCF8');
        $this->addSql('ALTER TABLE goal DROP CONSTRAINT FK_FCDCEB2EA9425B7A');
        $this->addSql('ALTER TABLE goal DROP CONSTRAINT FK_FCDCEB2E3EB8070A');
        $this->addSql('ALTER TABLE goal DROP CONSTRAINT FK_FCDCEB2EC86F3B2F');
        $this->addSql('ALTER TABLE goal DROP CONSTRAINT FK_FCDCEB2EAC78BCF8');
        $this->addSql('ALTER TABLE metric_definition DROP CONSTRAINT FK_DADB9D15AC78BCF8');
        $this->addSql('ALTER TABLE personal_record DROP CONSTRAINT FK_6FB87386E934951A');
        $this->addSql('ALTER TABLE personal_record DROP CONSTRAINT FK_6FB87386A9425B7A');
        $this->addSql('ALTER TABLE personal_record DROP CONSTRAINT FK_6FB87386850C57DF');
        $this->addSql('ALTER TABLE program_week DROP CONSTRAINT FK_56BC3CC73EB8070A');
        $this->addSql('ALTER TABLE session DROP CONSTRAINT FK_D044D5D4C86F3B2F');
        $this->addSql('ALTER TABLE session DROP CONSTRAINT FK_D044D5D4AC78BCF8');
        $this->addSql('ALTER TABLE session_log DROP CONSTRAINT FK_F2E6F0FF613FECDF');
        $this->addSql('DROP TABLE activity');
        $this->addSql('DROP TABLE activity_log');
        $this->addSql('DROP TABLE activity_metric');
        $this->addSql('DROP TABLE exercise');
        $this->addSql('DROP TABLE exercise_metric_default');
        $this->addSql('DROP TABLE exercise_type');
        $this->addSql('DROP TABLE goal');
        $this->addSql('DROP TABLE metric_definition');
        $this->addSql('DROP TABLE personal_record');
        $this->addSql('DROP TABLE program');
        $this->addSql('DROP TABLE program_week');
        $this->addSql('DROP TABLE session');
        $this->addSql('DROP TABLE session_log');
        $this->addSql('DROP TABLE sport');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
